language: python
python:
  - "2.7"

cache:
  directories:
    - $HOME/.cache/pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

git:
  depth: false

env:
  global:
    - CCNET_CONF_DIR=/tmp/ccnet SEAFILE_CONF_DIR=/tmp/seafile-data

before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > ~/.npmrc
  - npm install -g requirejs

  # build/init/start ccnet-server/seafile-server
  - git clone --depth=1 --branch=7.0 git://github.com/haiwen/seafile-test-deploy /tmp/seafile-test-deploy
  - cd /tmp/seafile-test-deploy && ./bootstrap.sh && cd -

install:
  - pip install pylibmc==1.6.0 django-pylibmc==0.6.1
  - pip install --timeout=3600 Pillow==4.3.0
  - pip install psd-tools==1.4
  - pip install -r dev-requirements.txt
  - pip install -r test-requirements.txt

script:
  - .travis/pingan-make-dist.sh

branches:
  only:
    - pingan-7.0
